### Documentation

http://localhost:5000

### Blockchain status

http://localhost:5000/blockchain

### Blocks index

http://localhost:5000/blocks

### Block details

http://localhost:5000/blocks/d02cbd2d697ec0e804b4527d36162c47643c9b890e4450da8b728bf8c139eaf3

### Block creation

POST http://localhost:5000/blocks

### Wallet balance

http://localhost:5000/wallet/lior

### Wallet balance and outputs

http://localhost:5000/wallet/lior?details=true

### Mempool transactions

http://localhost:5000/mempool

### Transaction creation

POST http://localhost:5000/transactions

{
	"to": "waiFu",
	"amount": 51
}

###
